- ros_topic_name: "clock"
  gz_topic_name: "clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "gz.msgs.Clock"
  direction: GZ_TO_ROS

- ros_topic_name: "/scan"
  gz_topic_name: "/scan"
  ros_type_name: "sensor_msgs/msg/LaserScan"
  gz_type_name: "gz.msgs.LaserScan"
  direction: GZ_TO_ROS

- ros_topic_name: "/point_cloud"
  gz_topic_name: "/scan/points"
  ros_type_name: "sensor_msgs/msg/PointCloud2"
  gz_type_name: "gz.msgs.PointCloudPacked"
  direction: GZ_TO_ROS

- ros_topic_name: "/imu"
  gz_topic_name: "/imu"
  ros_type_name: "sensor_msgs/msg/Imu"
  gz_type_name: "gz.msgs.IMU"
  direction: GZ_TO_ROS

- ros_topic_name: "rgbd_camera/points"
  gz_topic_name: "rgbd_camera/points"
  ros_type_name: "sensor_msgs/msg/PointCloud2"
  gz_type_name: "gz.msgs.PointCloudPacked"
  direction: GZ_TO_ROS

- ros_topic_name: "/cmd_vel"
  gz_topic_name: "/cmd_vel"
  ros_type_name: "geometry_msgs/msg/Twist"
  gz_type_name: "gz.msgs.Twist"
  direction: ROS_TO_GZ

- ros_topic_name: "/mirte_base_controller/odom"
  gz_topic_name: "/odometry"
  ros_type_name: "nav_msgs/msg/Odometry"
  gz_type_name: "gz.msgs.Odometry"
  direction: GZ_TO_ROS

- ros_topic_name: "/joint_states"
  gz_topic_name: "/mirte/joint_states"
  ros_type_name: "sensor_msgs/msg/JointState"
  gz_type_name: "gz.msgs.Model"
  direction: GZ_TO_ROS

- ros_topic_name: "tf"
  gz_topic_name: "/tf"
  ros_type_name: "tf2_msgs/msg/TFMessage"
  gz_type_name: "gz.msgs.Pose_V"
  direction: BIDIRECTIONAL

# intensity sensor(camera), /camera_{lef,right}/image_raw, /camera_{left,right}/cam_info
- ros_topic_name: "/mirte/camera_ir_left/image_raw"
  gz_topic_name: "/camera_left/image_raw"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: GZ_TO_ROS
- ros_topic_name: "/mirte/camera_ir_left/cam_info"
  gz_topic_name: "/camera_left/cam_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "gz.msgs.CameraInfo"
  direction: GZ_TO_ROS
- ros_topic_name: "/mirte/camera_ir_right/image_raw"
  gz_topic_name: "/camera_right/image_raw"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: GZ_TO_ROS
- ros_topic_name: "/mirte/camera_ir_right/cam_info"
  gz_topic_name: "/camera_right/cam_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "gz.msgs.CameraInfo"
  direction: GZ_TO_ROS

# sonars: /mirte/scanSonarleft to /mirte/distance/left, /mirte/scanSonarright to /mirte/distance/right
# range message out of range is wrong, will give max_range+1, not +inf: https://www.ros.org/reps/rep-0117.html
- ros_topic_name: "/mirte/distance/left"
  gz_topic_name: "/mirte/scanSonarleft"
  ros_type_name: "sensor_msgs/msg/Range"
  gz_type_name: "gz.msgs.LaserScan"
  direction: GZ_TO_ROS
- ros_topic_name: "/mirte/distance/right"
  gz_topic_name: "/mirte/scanSonarright"
  ros_type_name: "sensor_msgs/msg/Range"
  gz_type_name: "gz.msgs.LaserScan"
  direction: GZ_TO_ROS

# bridge /model/mirte/pose to /mirte/pose
- ros_topic_name: "/mirte/pose"
  gz_topic_name: "/model/mirte/pose"
  ros_type_name: "geometry_msgs/msg/PoseStamped"
  gz_type_name: "gz.msgs.Pose"
  direction: GZ_TO_ROS