name: test-clang-format
on: [push, pull_request]
jobs:
  cpp_style_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: DoozyX/clang-format-lint-action@v0.20
        with:
          source: '.'
          # exclude: './third_party ./external'
          extensions: 'h,cpp,hpp,c'
          clangFormatVersion: 18
          style: llvm
